# Generated by Django 3.1 on 2020-09-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_auto_20200922_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan1m',
            name='tanggal',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
