# Generated by Django 3.1 on 2020-09-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_auto_20200915_0721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penjualan',
            new_name='PenjualanTunai',
        ),
    ]
