# Generated by Django 3.1 on 2020-09-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0003_auto_20200915_0807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PenjualanTunai',
            new_name='Penjualan',
        ),
    ]
