# Generated by Django 3.1 on 2020-09-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_auto_20200925_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangm',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barangm',
            name='harga_jual',
            field=models.IntegerField(default=0),
        ),
    ]
