# Generated by Django 3.1 on 2020-09-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0004_auto_20200925_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldoawalm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_awal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='barangm',
            name='harga_beli',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
