# Generated by Django 3.1 on 2020-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_artis'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='artis',
            field=models.TextField(default=''),
        ),
    ]
