# Generated by Django 3.1 on 2020-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.TextField(default='')),
                ('customeraddress', models.TextField(default='')),
                ('customercontact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.TextField(default='')),
                ('itemprice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.TextField(default='')),
                ('supplieraddress', models.TextField(default='')),
                ('suppliercontact', models.IntegerField(default=0)),
            ],
        ),
    ]
