# Generated by Django 3.1 on 2020-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_customer_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemsaleprice',
            field=models.IntegerField(default=0),
        ),
    ]
