# Generated by Django 3.1 on 2020-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_item_itemsaleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customercontact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliercontact',
            field=models.TextField(default=''),
        ),
    ]
