# Generated by Django 3.1.2 on 2020-10-13 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='barangm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=200)),
                ('harga_beli', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='barang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_awal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='utangm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('catatan', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=10)),
                ('jatuh_tempo', models.DateField(default=datetime.datetime.now)),
                ('dibayar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='saldoawalm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_awal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saldoawal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan1m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kuantitas', models.IntegerField(default=0)),
                ('saldo_awal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('kas_masuk', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('terima', models.IntegerField(default=0)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='penjualan', to='olshop.barangm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='penjualan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pend_lainm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('pendapatan', models.DecimalField(decimal_places=0, max_digits=10)),
                ('kas_masuk', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('terima', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pendlain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pembayaran_lainm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('dibayar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('utang', models.DecimalField(decimal_places=0, max_digits=10)),
                ('catatan', models.CharField(max_length=200)),
                ('dibayar3', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pembayaranlain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pembayaran_biayam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('dibayar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('catatan', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pembiaya', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pem_tunaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('pembelian', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('kas_keluar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dibayar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pemtunai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pem_lainm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('dibayar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('utang', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('catatan', models.CharField(max_length=200)),
                ('dibayar2', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pemlain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pem_kreditm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kuantitas', models.IntegerField(default=0)),
                ('kas_keluar', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('dibayar1', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('barang', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='olshop.barangm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pemkredit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
