# Generated by Django 3.1.2 on 2020-10-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan1m',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olshop.barangm'),
        ),
    ]
