# Generated by Django 3.1 on 2020-10-01 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_auto_20201001_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan2m',
            name='tanggal',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
