# Generated by Django 3.1.2 on 2020-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan1m',
            name='terima',
            field=models.IntegerField(default=0),
        ),
    ]
