# Generated by Django 3.1.2 on 2020-10-08 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_penjualan1m_terima'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangm',
            name='jatuh_tempo',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
