# Generated by Django 3.1.2 on 2020-10-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0004_auto_20201008_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utangm',
            old_name='tempo',
            new_name='jatuh_tempo',
        ),
    ]
