# Generated by Django 3.1.2 on 2020-10-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0006_auto_20201009_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pem_kreditm',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='pem_kreditm',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='pem_kreditm',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='pem_kreditm',
            name='barang',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='olshop.barangm'),
        ),
        migrations.AddField(
            model_name='pem_kreditm',
            name='kas_keluar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pem_kreditm',
            name='kuantitas',
            field=models.IntegerField(default=0),
        ),
    ]
