# Generated by Django 2.2 on 2020-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default='tanggal', max_length=255)),
                ('keterangan', models.CharField(default='Keterangan', max_length=255)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(default='Catatan', max_length=255)),
            ],
        ),
    ]
