# Generated by Django 3.1 on 2020-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pend_lainm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='penjualan1m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('barang', models.CharField(max_length=200)),
                ('kuantitas', models.IntegerField(default=0)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='penjualan2m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('barang', models.CharField(max_length=200)),
                ('kuantitas', models.IntegerField(default=0)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='penjualan3m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('kas', models.IntegerField(default=0)),
                ('piutang', models.IntegerField(default=0)),
                ('catatan', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='utangm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catatan', models.TextField(default='')),
            ],
        ),
    ]
