# Generated by Django 3.1 on 2020-09-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_auto_20200916_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='penjualan1m',
            options={'ordering': ['barang']},
        ),
    ]
