# Generated by Django 3.1 on 2020-09-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0003_auto_20200916_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangm',
            options={'ordering': ['barang']},
        ),
        migrations.AlterModelOptions(
            name='penjualan1m',
            options={},
        ),
        migrations.AlterField(
            model_name='penjualan1m',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olshop.barangm'),
        ),
    ]
