# Generated by Django 3.1 on 2020-09-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0004_auto_20200916_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangm',
            options={},
        ),
        migrations.AlterField(
            model_name='penjualan1m',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='olshop.barangm'),
        ),
    ]
