# Generated by Django 3.1 on 2020-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_auto_20200916_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan1m',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='penjualan2m',
            name='jumlah',
        ),
        migrations.AlterField(
            model_name='barangm',
            name='harga_beli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barangm',
            name='harga_jual',
            field=models.IntegerField(default=0),
        ),
    ]
