# Generated by Django 3.1 on 2020-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0006_pembayaran_lainm'),
    ]

    operations = [
        migrations.CreateModel(
            name='barangm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=200)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
