# Generated by Django 3.1 on 2020-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0007_penjualan2m_terima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pem_lainm',
            name='jumlah',
        ),
        migrations.AddField(
            model_name='pem_lainm',
            name='dibayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pem_lainm',
            name='utang',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
