# Generated by Django 3.1 on 2020-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0008_auto_20200917_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='utangm',
            name='dibayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
