# Generated by Django 3.1 on 2020-09-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0008_saldom'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangm',
            name='saldo_awal',
            field=models.IntegerField(default=0),
        ),
    ]
