# Generated by Django 3.1 on 2020-09-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0010_auto_20200917_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pem_lainm',
            name='dibayar1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
