# Generated by Django 3.1 on 2020-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0011_pem_lainm_dibayar1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pem_lainm',
            name='dibayar1',
        ),
        migrations.AddField(
            model_name='pem_kreditm',
            name='dibayar1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
