# Generated by Django 3.1 on 2020-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0013_pem_lainm_dibayar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangm',
            name='saldo_awal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
