# Generated by Django 3.1 on 2020-09-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0014_barangm_saldo_awal'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_awal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='barangm',
            name='saldo_awal',
        ),
    ]
