# Generated by Django 3.1 on 2020-09-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0015_auto_20200917_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saldom',
        ),
        migrations.AddField(
            model_name='penjualan1m',
            name='saldo_awal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
