# Generated by Django 3.1 on 2020-09-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0016_auto_20200918_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pend_lainm',
            name='piutang',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
