# Generated by Django 3.1 on 2020-09-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0017_pend_lainm_piutang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pend_lainm',
            name='terima',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
