# Generated by Django 3.1 on 2020-09-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0018_pend_lainm_terima'),
        ('olshop', '0009_barangm_saldo_awal'),
    ]

    operations = [
    ]
