# Generated by Django 3.1.2 on 2020-10-19 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan1m',
            name='saldo_awal',
        ),
        migrations.AddField(
            model_name='penjualan1m',
            name='jatuh_tempo',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
