# Generated by Django 3.1.2 on 2020-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0004_auto_20201019_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan1m',
            name='jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
