# Generated by Django 3.1.2 on 2020-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_auto_20201019_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='pend_lainm',
            name='jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
