# Generated by Django 3.1.2 on 2020-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0006_pend_lainm_jatuh_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utangm',
            name='jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
