# Generated by Django 3.1 on 2020-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lain',
            name='catatan',
            field=models.CharField(max_length=255),
        ),
    ]
