# Generated by Django 3.1 on 2020-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_artis'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='th',
            field=models.TextField(default=''),
        ),
    ]
