# Generated by Django 3.1 on 2020-09-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('gen', models.TextField(default='')),
                ('rate', models.TextField(default='')),
                ('years', models.TextField(default='')),
                ('des', models.TextField(default='')),
            ],
        ),
    ]
