# Generated by Django 3.1 on 2020-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjualan',
            old_name='name',
            new_name='nama_barang',
        ),
        migrations.RenameField(
            model_name='penjualan',
            old_name='done_at',
            new_name='tanggal_transaksi',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='description',
        ),
        migrations.AddField(
            model_name='penjualan',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='jumlah_barang',
            field=models.IntegerField(default=0),
        ),
    ]
