# Generated by Django 3.1 on 2020-09-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0002_auto_20200914_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
