# Generated by Django 3.1 on 2020-09-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0003_auto_20200914_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penjualan',
            old_name='harga',
            new_name='harga_satuan',
        ),
    ]
