# Generated by Django 3.1 on 2020-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0004_auto_20200914_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='tanggal_transaksi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
    ]
