# Generated by Django 3.1 on 2020-09-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kas', '0005_auto_20200914_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='tanggal_transaksi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
