# Generated by Django 3.1 on 2020-09-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Elektronik',
        ),
    ]
