# Generated by Django 3.1 on 2020-09-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200908_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('update', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='des',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='gen',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='th',
            new_name='tahun',
        ),
    ]
