# Generated by Django 3.1 on 2020-09-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200908_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='years',
            new_name='tahun',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='link',
            new_name='album',
        ),
    ]
